zsh_plugins_per_user:
  - username: alexis
    plugins:
      - {'name': 'gitfast'}
      - {'repo': 'https://github.com/zsh-users/zsh-autosuggestions.git', 'name': 'zsh-autosuggestions'}
      - {'repo': 'https://github.com/zsh-users/zsh-syntax-highlighting.git', 'name': 'zsh-syntax-highlighting'}
      - {'name': 'terraform'}
      - {'name': 'kubectl'}
      - {'name': 'kubectx'}
      - {'name': 'zoxide'}
      - {'name': 'command-not-found'}
      - {'name': 'fzf'}
      - {'name': 'gitignore'}
      - {'name': 'helm'}
      - {'name': 'sudo'}
  - username: root
    plugins:
      - {'name': 'gitfast'}
      - {'repo': 'https://github.com/zsh-users/zsh-autosuggestions.git', 'name': 'zsh-autosuggestions'}
      - {'repo': 'https://github.com/zsh-users/zsh-syntax-highlighting.git', 'name': 'zsh-syntax-highlighting'}
      - {'name': 'terraform'}
      - {'name': 'kubectl'}
      - {'name': 'kubectx'}
      - {'name': 'zoxide'}
      - {'name': 'command-not-found'}
      - {'name': 'fzf'}
      - {'name': 'gitignore'}
      - {'name': 'helm'}
      - {'name': 'sudo'}
