- name: Upgrade Fedora WSL to a new version
  hosts: localhost
  connection: local
  become: true
  vars_prompt:
    - name: fedora_upgrade_version
      prompt: "Enter the new Fedora version (e.g., 42)"
      private: false
      default: "42"
  pre_tasks:
    - name: Compare current and new Fedora versions
      ansible.builtin.assert:
        that:
          - (ansible_distribution_version | int) < (fedora_upgrade_version | int)
        fail_msg: "The current Fedora version is already {{ ansible_distribution_version }} or you're trying to downgrade to an older version."
  tasks:
    - name: Upgrade current Fedora  # noqa: package-latest
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: "Launch upgrade to {{ fedora_upgrade_version }}"  # noqa: no-changed-when
      ansible.builtin.command:
        cmd: "dnf distro-sync --releasever={{ fedora_upgrade_version }} --setopt=deltarpm=false"
    - name: Upgrade latest Fedora  # noqa: package-latest
      ansible.builtin.dnf:
        name: "*"
        state: latest
