---
- name: Ensure git is installed
  tags: git
  ansible.builtin.package:
    name:
      - git
      - gnupg
    state: present
- name: Setup default git configuration
  tags: git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: "core.editor", value: "vi" }
    - { name: "user.name", value: "{{ git.user.name }}" }
    - { name: "user.email", value: "{{ git.user.email }}" }
    - { name: "ui.color", value: "true" }
    - { name: "pull.rebase", value: "true" }
  become: true
  become_user: "{{ username_on_the_host }}"

- name: Setup GPG git configuration
  tags: git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  when: git.user.signingkey is defined
  with_items:
    - { name: "user.signingkey", value: "{{ git.user.signingkey }}" }
    - { name: "commit.gpgsign", value: "true" }
  become: true
  become_user: "{{ username_on_the_host }}"
