---
- name: Install prerequisites packages
  tags: pageant
  become_user: root
  ansible.builtin.package:
    name:
      - socat
      - iproute
    state: present

- name: Download file from remote
  tags: pageant
  become_user: "root"
  ansible.builtin.get_url:
    url: https://github.com/BlackReloaded/wsl2-ssh-pageant/releases/latest/download/wsl2-ssh-pageant.exe
    dest: "{{ pageant_windows_destination }}"
    mode: "0600"
    owner: "{{ username_on_the_host }}"
    group: "{{ username_on_the_host }}"

- name: Create .ssh directory if it does not exists
  tags: pageant
  become_user: "{{ username_on_the_host }}"
  ansible.builtin.file:
    dest: "~/.ssh"
    owner: "{{ username_on_the_host }}"
    group: "{{ username_on_the_host }}"
    mode: "0750"
    state: directory

- name: Create symlink between windows and linux
  tags: pageant
  become_user: "root"
  ansible.builtin.file:
    src: "{{ pageant_windows_destination }}"
    dest: "{{ ('/root' if item == 'root' else ('/home/' + item)) + pageant_linux_destination }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0755"
    state: link
  loop: "{{ zsh_users }}"

- name: Create .ssh directory if it does not exists
  tags: pageant
  become_user: "{{ username_on_the_host }}"
  ansible.builtin.template:
    src: templates/ssh/config.j2
    dest: "~/.ssh/config"
    owner: "{{ username_on_the_host }}"
    group: "{{ username_on_the_host }}"
    mode: "0600"
