---
- name: Ensure packages are installed
  tags: shell
  ansible.builtin.package:
    name: 
      - zsh
      - bat
      - dos2unix
      - zoxide
    state: present

- name: Clone oh-my-zsh repo
  tags: shell
  become: true
  become_user: "{{ item }}"
  loop: "{{ zsh_users }}"
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: Clone powerlevel10k repo
  tags: shell
  become: true
  become_user: "{{ item }}"
  loop: "{{ zsh_users }}"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: Install plugins
  tags: shell
  become: true
  become_user: "{{ item.0.username }}"
  ansible.builtin.git:
    repo: "{{ item.1.repo }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.1.name }}"
    depth: 1
  with_subelements:
    - "{{ zsh_plugins_per_user }}"
    - plugins
  when: item.1.repo is defined

- name: Set zsh as default shell
  tags: shell
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  loop: "{{ zsh_users }}"

- name: Push .zshrc configuration
  tags: shell
  become: true
  become_user: "{{ item }}"
  ansible.builtin.template:
    src: templates/zsh/.zshrc.j2
    dest: ~/.zshrc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0644"
  loop: "{{ zsh_users }}"

- name: Push .p10k.zsh configuration
  tags: shell
  become: true
  become_user: "{{ item }}"
  ansible.builtin.copy:
    src: files/zsh/.p10k.zsh
    dest: ~/.p10k.zsh
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0644"
  loop: "{{ zsh_users }}"
